export const LOAD_COMPANIES_SUCCESS = "LOAD_COMPANIES_SUCCESS";
export const TOGGLE_FLAG_BLOCK_MAP = "TOGGLE_FLAG_BLOCK_MAP";
export const LOAD_COMPANIES_STATS_ACTIVITIES_SUCCESS = "LOAD_COMPANIES_STATS_ACTIVITIES_SUCCESS";
export const LOAD_COMPANIES_ATTRIBUTES_DISTINCT_VALUES_SUCCESS = "LOAD_COMPANIES_ATTRIBUTES_DISTINCT_VALUES_SUCCESS";